package workos

import (
	"net/url"

	"github.com/golly-go/golly"
	"github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the WorkosClient type
type MockClient struct {
	mock.Mock
}

func (m *MockClient) JWKSURL() (*url.URL, error) {
	ret := m.Called()

	var r0 *url.URL
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*url.URL)
	}

	var r1 error
	if r, ok := ret.Get(1).(error); ok {
		r1 = r
	}

	return r0, r1

}

func (m *MockClient) CreateUser(ctx golly.Context, input CreateUserInput) (string, error) {
	ret := m.Called(ctx, input)

	var r0 string
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(string)
	}
	var r1 error
	if r, ok := ret.Get(1).(error); ok {
		r1 = r
	}
	return r0, r1
}

func (m *MockClient) CreateOrganization(ctx golly.Context, name string, users ...string) (string, error) {
	ret := m.Called(ctx, name, users)

	var r0 string
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(string)
	}
	var r1 error
	if r, ok := ret.Get(1).(error); ok {
		r1 = r
	}
	return r0, r1
}

func (m *MockClient) InviteUser(ctx golly.Context, orgID string, email string, inviterID string) (string, string, error) {
	ret := m.Called(ctx, orgID, email, inviterID)

	var r0 string
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if ret.Get(0) != nil {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if r, ok := ret.Get(2).(error); ok {
		r2 = r
	}

	return r0, r1, r2
}
